// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzgVw__jgM4ohvO5191_uWudkqWhEjCcg',
    appId: '1:840014416024:android:c044f6a6a5c5907629a8ed',
    messagingSenderId: '840014416024',
    projectId: 'ottersync-b4833',
    storageBucket: 'ottersync-b4833.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDkJsfI_dSH-He4Tba2G3oYgIgm1HMVMw',
    appId: '1:840014416024:web:1f5d4b89c4b8c07429a8ed',
    messagingSenderId: '840014416024',
    projectId: 'ottersync-b4833',
    authDomain: 'ottersync-b4833.firebaseapp.com',
    storageBucket: 'ottersync-b4833.firebasestorage.app',
    measurementId: 'G-M7GJV6PR2R',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU67cWkx8s6wFwobmWqm8w6NbEJAkeF2A',
    appId: '1:840014416024:ios:25e40acfbf4c058129a8ed',
    messagingSenderId: '840014416024',
    projectId: 'ottersync-b4833',
    storageBucket: 'ottersync-b4833.firebasestorage.app',
    iosBundleId: 'com.example.ottersync',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU67cWkx8s6wFwobmWqm8w6NbEJAkeF2A',
    appId: '1:840014416024:ios:25e40acfbf4c058129a8ed',
    messagingSenderId: '840014416024',
    projectId: 'ottersync-b4833',
    storageBucket: 'ottersync-b4833.firebasestorage.app',
    iosBundleId: 'com.example.ottersync',
  );

}