// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBWndFh9gSIp8MtYxtf7Dgv-baebgUCC0',
    appId: '1:785799948599:android:31ab403a3013f1349d12b2',
    messagingSenderId: '785799948599',
    projectId: 'ottersync-24da2',
    storageBucket: 'ottersync-24da2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfxn6ALmPDe09iwH382kWC0C_7rJ-F1C0',
    appId: '1:785799948599:web:301a3757662086289d12b2',
    messagingSenderId: '785799948599',
    projectId: 'ottersync-24da2',
    authDomain: 'ottersync-24da2.firebaseapp.com',
    storageBucket: 'ottersync-24da2.firebasestorage.app',
    measurementId: 'G-SNCZ943NKQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxolqD9qqr4TUd5RkethHAiJqGORT5LCM',
    appId: '1:785799948599:ios:2ee1804e00c045c79d12b2',
    messagingSenderId: '785799948599',
    projectId: 'ottersync-24da2',
    storageBucket: 'ottersync-24da2.firebasestorage.app',
    iosBundleId: 'com.example.ottersync',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxolqD9qqr4TUd5RkethHAiJqGORT5LCM',
    appId: '1:785799948599:ios:2ee1804e00c045c79d12b2',
    messagingSenderId: '785799948599',
    projectId: 'ottersync-24da2',
    storageBucket: 'ottersync-24da2.firebasestorage.app',
    iosBundleId: 'com.example.ottersync',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfxn6ALmPDe09iwH382kWC0C_7rJ-F1C0',
    appId: '1:785799948599:web:d6cb1923aef7dc779d12b2',
    messagingSenderId: '785799948599',
    projectId: 'ottersync-24da2',
    authDomain: 'ottersync-24da2.firebaseapp.com',
    storageBucket: 'ottersync-24da2.firebasestorage.app',
    measurementId: 'G-JCLL06FLFS',
  );

}