[project]
name = "src"
version = "0.1.0"
description = "OtterSync's backend"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.136.0",
    "openapi>=2.0.0",
    "openapi-generator-cli>=7.21.0",
    "pydantic-settings>=2.11.0",
    "sqlmodel>=0.0.38",
]

[project.scripts]
export-openapi = "export_openapi:export_openapi_schema"

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pytest>=8.4.2",
    "ruff>=0.14.1",
]
